# Generated by Django 5.2.1 on 2025-05-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("Reminder_time", models.DateTimeField()),
                (
                    "Reminder_method",
                    models.CharField(
                        choices=[("sms", "SMS"), ("email", "Email")], max_length=10
                    ),
                ),
                ("recipient", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Reminder",
                "verbose_name_plural": "Reminders",
                "ordering": ["date", "time"],
            },
        ),
    ]
