# Generated by Django 5.2.1 on 2025-05-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reminder",
            name="Reminder_time",
        ),
    ]
