# Generated by Django 5.2.1 on 2025-05-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_reminder_reminder_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reminder",
            name="recipient",
        ),
    ]
